export const sample_foods: any[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    stars: 3.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 4.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id: '7',
    name: 'Tacos',
    price: 8,
    cookTime: '10-15',
    favorite: true,
    origins: ['mexico'],
    stars: 4.3,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Mexican', 'Snack'],
  },
  {
    id: '8',
    name: 'Spaghetti Carbonara',
    price: 12,
    cookTime: '20-30',
    favorite: true,
    origins: ['italy'],
    stars: 4.8,
    imageUrl: 'assets/food-8.jpg',
    tags: ['Pasta', 'Italian', 'Dinner'],
  },
  {
    id: '9',
    name: 'Sushi',
    price: 18,
    cookTime: '30-40',
    favorite: false,
    origins: ['japan'],
    stars: 4.6,
    imageUrl: 'assets/food-9.jpg',
    tags: ['Seafood', 'Japanese', 'Dinner'],
  },
  {
    id: '10',
    name: 'Pad Thai',
    price: 13,
    cookTime: '25-35',
    favorite: true,
    origins: ['thailand'],
    stars: 4.7,
    imageUrl: 'assets/food-10.jpg',
    tags: ['Noodles', 'Thai', 'Dinner'],
  },
  {
    id: '11',
    name: 'Croissant',
    price: 4,
    cookTime: '15-20',
    favorite: false,
    origins: ['france'],
    stars: 4.1,
    imageUrl: 'assets/food-11.jpg',
    tags: ['Breakfast', 'Bakery', 'Snack'],
  },
  {
    id: '12',
    name: 'Ramen',
    price: 14,
    cookTime: '30-40',
    favorite: true,
    origins: ['japan'],
    stars: 4.5,
    imageUrl: 'assets/food-12.jpg',
    tags: ['Soup', 'Japanese', 'Dinner'],
  },
  {
    id: '13',
    name: 'Falafel Wrap',
    price: 7,
    cookTime: '10-15',
    favorite: false,
    origins: ['middle east'],
    stars: 4.2,
    imageUrl: 'assets/food-13.jpeg',
    tags: ['FastFood', 'Snack', 'Lunch'],
  },
  {
    id: '14',
    name: 'Cheeseburger',
    price: 6,
    cookTime: '10-20',
    favorite: true,
    origins: ['us'],
    stars: 4.4,
    imageUrl: 'assets/food-14.jpeg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id: '15',
    name: 'Penne Arrabbiata',
    price: 11,
    cookTime: '20-30',
    favorite: false,
    origins: ['italy'],
    stars: 4.1,
    imageUrl: 'assets/food-15.jpeg',
    tags: ['Pasta', 'Italian', 'Dinner'],
  },
  {
    id: '16',
    name: 'Fish and Chips',
    price: 10,
    cookTime: '15-25',
    favorite: true,
    origins: ['uk'],
    stars: 4.5,
    imageUrl: 'assets/food-16.jpeg',
    tags: ['FastFood', 'Snack', 'Lunch'],
  },
  {
    id: '17',
    name: 'Margherita Pizza',
    price: 9,
    cookTime: '20-30',
    favorite: true,
    origins: ['italy'],
    stars: 4.6,
    imageUrl: 'assets/food-17.jpeg',
    tags: ['Pizza', 'Italian', 'Lunch'],
  },
  {
    id: '18',
    name: 'Doner Kebab',
    price: 8,
    cookTime: '10-15',
    favorite: false,
    origins: ['turkey'],
    stars: 4.3,
    imageUrl: 'assets/food-18.jpeg',
    tags: ['FastFood', 'Snack', 'Dinner'],
  },
  {
    id: '19',
    name: 'Vegetable Stir-Fry',
    price: 12,
    cookTime: '15-25',
    favorite: true,
    origins: ['china'],
    stars: 4.7,
    imageUrl: 'assets/food-19.jpeg',
    tags: ['FastFood', 'Vegetarian', 'Dinner'],
  },
  {
    id: '20',
    name: 'BBQ Chicken Wings',
    price: 13,
    cookTime: '20-30',
    favorite: true,
    origins: ['us'],
    stars: 4.5,
    imageUrl: 'assets/food-20.jpeg',
    tags: ['FastFood', 'Snack', 'Dinner'],
  },
];

export const sample_tags: any[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
];

export const sample_users: any[] = [
  {
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: true,
  },
  {
    name: 'Jane Doe',
    email: 'Jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: false,
  },
];
